### ISSUE TITLE
Eventmachine gem install error

### ISSUE THREAD

**Issue by raybesiga** [tryshoppe/shoppe-example#5]
When I run bundle, it runs smoothly until it gives this error:

```ruby
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing rake 10.1.0
Installing i18n 0.6.5
Installing minitest 4.7.5
Installing multi_json 1.8.2
with native extensions Installing atomic 1.1.14
Installing thread_safe 0.1.3
Installing tzinfo 0.3.38
Installing activesupport 4.0.1
Installing builder 3.1.4
Using erubis 2.7.0
Installing rack 1.5.2
Installing rack-test 0.6.2
Installing actionpack 4.0.1
Installing mime-types 1.25.1
Installing polyglot 0.3.3
Installing treetop 1.4.15
Installing mail 2.5.4
Installing actionmailer 4.0.1
Installing activemodel 4.0.1
Installing activerecord-deprecated_finders 1.0.3
Installing arel 4.0.1
Installing activerecord 4.0.1
with native extensions Installing bcrypt-ruby 3.1.2
Installing highline 1.6.19
Installing net-ssh 2.7.0
Installing net-scp 1.1.2
Installing net-sftp 2.1.2
Installing net-ssh-gateway 1.2.0
Installing capistrano 2.15.5
Installing coffee-script-source 1.6.3
Installing execjs 2.0.2
Installing coffee-script 2.2.0
Installing thor 0.18.1
Installing railties 4.0.1
Installing coffee-rails 4.0.1
Installing daemons 1.1.9
Using dynamic_form 1.1.4
with native extensions 
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/raybesiga/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150617-53376-1la4gct.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
compiling cmain.cpp
compiling ed.cpp
compiling em.cpp
em.cpp:827:9: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
               ^~~~~~~~
               rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select
                   ^
/Users/raybesiga/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
em.cpp:827:32: error: cannot initialize a parameter of type 'rb_fdset_t *' with an rvalue of type 'fd_set *'
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
                                      ^~~~~~~~
/Users/raybesiga/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/intern.h:454:42: note: passing argument to parameter here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
                                         ^
em.cpp:946:6: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
                                        EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^~~~~~~~
                                        rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select
                   ^
/Users/raybesiga/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
3 errors generated.
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.0.3 for inspection.
Results logged to /Users/raybesiga/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/eventmachine-1.0.3/gem_make.out
An error occurred while installing eventmachine (1.0.3), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
```
After this I run "gem install eventmachine -v '1.0.3'" and it still gave the error:

```ruby
Fetching: eventmachine-1.0.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /Users/raybesiga/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150617-54354-1qex3gx.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
compiling cmain.cpp
compiling ed.cpp
compiling em.cpp
em.cpp:827:9: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
               ^~~~~~~~
               rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select
                   ^
/Users/raybesiga/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
em.cpp:827:32: error: cannot initialize a parameter of type 'rb_fdset_t *' with an rvalue of type 'fd_set *'
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
                                      ^~~~~~~~
/Users/raybesiga/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/intern.h:454:42: note: passing argument to parameter here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
                                         ^
em.cpp:946:6: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
                                        EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^~~~~~~~
                                        rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select
                   ^
/Users/raybesiga/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
3 errors generated.
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.0.3 for inspection.
Results logged to /Users/raybesiga/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/eventmachine-1.0.3/gem_make.out
```

Anyone have ideas what is causing this?

**Comment by deanperry** [comment]
Does this help? https://github.com/eventmachine/eventmachine/issues/553

**Comment by raybesiga** [comment]
It indeed helped but a new problem arose. I updated the Gemfile and Gemfile.lock files as follows.

Gemfile:
```ruby
source 'https://rubygems.org'
gem 'rails', '4.0.1'
gem 'sqlite3'
gem 'mysql2'
gem 'haml'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'redcarpet'
gem 'faker'
gem 'shoppe', '~> 0.0.20'
gem 'thin'

group :development do
  gem 'capistrano'
end
```

Gemfile.lock:
```ruby
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.0.1)
      actionpack (= 4.0.1)
      mail (~> 2.5.4)
    actionpack (4.0.1)
      activesupport (= 4.0.1)
      builder (~> 3.1.0)
      erubis (~> 2.7.0)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    activemodel (4.0.1)
      activesupport (= 4.0.1)
      builder (~> 3.1.0)
    activerecord (4.0.1)
      activemodel (= 4.0.1)
      activerecord-deprecated_finders (~> 1.0.2)
      activesupport (= 4.0.1)
      arel (~> 4.0.0)
    activerecord-deprecated_finders (1.0.3)
    activesupport (4.0.1)
      i18n (~> 0.6, >= 0.6.4)
      minitest (~> 4.2)
      multi_json (~> 1.3)
      thread_safe (~> 0.1)
      tzinfo (~> 0.3.37)
    arel (4.0.1)
    atomic (1.1.14)
    bcrypt-ruby (3.1.2)
    builder (3.1.4)
    capistrano (2.15.5)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.3)
    daemons (1.1.9)
    dynamic_form (1.1.4)
    erubis (2.7.0)
    eventmachine (1.0.4)
    execjs (2.0.2)
    faker (1.1.2)
      i18n (~> 0.5)
    haml (4.0.3)
      tilt
    highline (1.6.19)
    hike (1.2.3)
    i18n (0.6.5)
    jquery-rails (3.0.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    kaminari (0.14.1)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.25.1)
    minitest (4.7.5)
    multi_json (1.8.2)
    mysql2 (0.3.18)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.7.0)
    net-ssh-gateway (1.2.0)
      net-ssh (>= 2.6.5)
    nifty-attachments (1.0.0)
    nifty-dialog (1.0.1)
    nifty-key-value-store (1.0.0)
    nifty-utils (1.0.0)
    polyamorous (0.6.4)
      activerecord (>= 3.0)
    polyglot (0.3.3)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.0.1)
      actionmailer (= 4.0.1)
      actionpack (= 4.0.1)
      activerecord (= 4.0.1)
      activesupport (= 4.0.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.1)
      sprockets-rails (~> 2.0.0)
    railties (4.0.1)
      actionpack (= 4.0.1)
      activesupport (= 4.0.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.1.0)
    ransack (1.0.0)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      polyamorous (~> 0.6.0)
    redcarpet (3.0.0)
    sass (3.2.12)
    sass-rails (4.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (>= 3.1.10)
      sprockets-rails (~> 2.0.0)
    shoppe (0.0.20)
      bcrypt-ruby (~> 3.1.2)
      coffee-rails (~> 4.0.0)
      dynamic_form (~> 1.1.4)
      haml (~> 4.0.3)
      jquery-rails (~> 3.0.4)
      kaminari (~> 0.14.1)
      nifty-attachments (~> 1.0.0)
      nifty-dialog (~> 1.0.0)
      nifty-key-value-store (~> 1.0.0)
      nifty-utils (~> 1.0.0)
      rails (~> 4.0.1)
      ransack (~> 1.0.0)
      sass-rails (~> 4.0.0)
      uglifier (>= 2.2.0)
    sprockets (2.10.1)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.0.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (~> 2.8)
    sqlite3 (0.0.0)
    thin (1.6.1)
      daemons (>= 1.0.9)
      eventmachine (>= 1.0.0)
      rack (>= 1.0.0)
    thor (0.18.1)
    thread_safe (0.1.3)
      atomic
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.38)
    uglifier (2.2.1)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  capistrano
  coffee-rails (~> 4.0.0)
  faker
  haml
  jquery-rails
  mysql2
  rails (= 4.0.1)
  redcarpet
  sass-rails (~> 4.0.0)
  shoppe (~> 0.0.20)
  sqlite3
  thin
  uglifier (>= 1.3.0)

BUNDLED WITH
   1.10.3
```

It throws a strange exception when i run 'rake db:schema:load shoppe:setup shoppe:seed'

```ruby
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
rake aborted!
Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile.
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activerecord-4.0.1/lib/active_record/connection_adapters/connection_specification.rb:58:in `rescue in resolve_hash_connection'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activerecord-4.0.1/lib/active_record/connection_adapters/connection_specification.rb:55:in `resolve_hash_connection'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activerecord-4.0.1/lib/active_record/connection_adapters/connection_specification.rb:46:in `resolve_string_connection'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activerecord-4.0.1/lib/active_record/connection_adapters/connection_specification.rb:30:in `spec'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activerecord-4.0.1/lib/active_record/connection_handling.rb:39:in `establish_connection'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activerecord-4.0.1/lib/active_record/railtie.rb:176:in `block (2 levels) in <class:Railtie>'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activerecord-4.0.1/lib/active_record/railtie.rb:174:in `block in <class:Railtie>'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/railties-4.0.1/lib/rails/initializable.rb:30:in `instance_exec'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/railties-4.0.1/lib/rails/initializable.rb:30:in `run'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/railties-4.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/railties-4.0.1/lib/rails/initializable.rb:54:in `run_initializers'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/railties-4.0.1/lib/rails/application.rb:215:in `initialize!'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/railties-4.0.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/raybesiga/Documents/shoppe-example/config/environment.rb:5:in `<top (required)>'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/railties-4.0.1/lib/rails/application.rb:189:in `require_environment!'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/railties-4.0.1/lib/rails/application.rb:250:in `block in run_tasks_blocks'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/raybesiga/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:load => environment
(See full trace by running task with --trace)
```
This is despite the fact that i have "gem 'sqlite3'" in my Gemfile

**Comment by deanperry** [comment]
It says the `sqlite3` gem is at version `0.0.0` for some reason. Try a `bundle update sqlite3`

**Comment by raybesiga** [comment]
Top lad @deanperry! It worked. One last little thing:

When i run the server, it gives me a warning:

```ruby
/Users/raybesiga/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.1/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
=> Booting Thin
=> Rails 4.0.1 application starting in development on http://0.0.0.0:3030
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Thin web server (v1.6.1 codename Death Proof)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
```
Thoughts?

**Comment by deanperry** [comment]
Looks like that's a Compass issue - http://stackoverflow.com/questions/27717309/how-do-i-avoid-the-circular-argument-reference-warning-in-activesupport

**Comment by raybesiga** [comment]
Thank you so much!
